### ISSUE TITLE
handling the end of the episode

### ISSUE THREAD

**Issue by rizar** [lcswillems/pytorch-a2c-ppo#8]
Here is a very trick RL detail which is often overlooked. I think it can be important when your episodes are not very long and your discount is large.

When the advantage is estimated for the last step of the episode, the current code computes it as A_t = r_t - V_t. One can argue that for modelling infinite episodes a more appropriate estimate is A_t = r_t + \gamma V_{t+1} - V_t. It is used broadly, e.g. in the [PPO paper](https://arxiv.org/abs/1707.06347). 

There is nothing too wrong with A_t = r_t - V_t if we optimize for finite episodes, or if we have a genuine episode termination (which is the case in Baby AI), so I guess I will just leave this here as food for thought.

**Comment by lcswillems** [comment]
If R_t is the return from timestep t, then the advantage at timestep t is A_t = R_t - V_t. So, you argue that if t is the last timestep of an episode (i.e. s_t is terminal), then R_t should be  r_t + \gamma V_{t+1} instead of r_t. But, s_{t+1} is not a state of the same episode, the return we can get from this state will not be added to the return we already got. So, I don't see why we should add it to the return.
